Load heart disease dataset in pandas dataframe. 

Remove outliers using Z score. Usual guideline is to remove anything that has Z score > 3 formula or Z score < -3

Convert text columns to numbers using label encoding and one hot encoding

Apply scaling 

Build a classification model using various methods (SVM, logistic regression, random forest) and check which model gives you the best accuracy 

Now use PCA to reduce dimensions, retrain your model and see what impact it has on your model in terms of accuracy. Keep in mind that many times doing PCA reduces the accuracy but computation is much lighter and that's the trade off you need to consider while building models in real life

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [15]:
df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [16]:
df=pd.get_dummies(df,drop_first=True)

In [17]:
df

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease  \
0     40        140          289          0    172      0.0             0   
1     49        160          180          0    156      1.0             1   
2     37        130          283          0     98      0.0             0   
3     48        138          214          0    108      1.5             1   
4     54        150          195          0    122      0.0             0   
..   ...        ...          ...        ...    ...      ...           ...   
913   45        110          264          0    132      1.2             1   
914   68        144          193          1    141      3.4             1   
915   57        130          131          0    115      1.2             1   
916   57        130          236          0    174      0.0             1   
917   38        138          175          0    173      0.0             0   

     Sex_M  ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  \
0        1                  1                  0                 0   
1        0                  0                  1                 0   
2        1                  1                  0                 0   
3        0                  0                  0                 0   
4        1                  0                  1                 0   
..     ...                ...                ...               ...   
913      1                  0                  0                 1   
914      1                  0                  0                 0   
915      1                  0                  0                 0   
916      0                  1                  0                 0   
917      1                  0                  1                 0   

     RestingECG_Normal  RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  \
0                    1              0                 0              0   
1                    1              0                 0              1   
2                    0              1                 0              0   
3                    1              0                 1              1   
4                    1              0                 0              0   
..                 ...            ...               ...            ...   
913                  1              0                 0              1   
914                  1              0                 0              1   
915                  1              0                 1              1   
916                  0              0                 0              1   
917                  1              0                 0              0   

     ST_Slope_Up  
0              1  
1              0  
2              1  
3              0  
4              1  
..           ...  
913            0  
914            0  
915            0  
916            0  
917            1  

[918 rows x 16 columns]

In [18]:
input=df.drop('HeartDisease',axis='columns')
input.head()

Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  Sex_M  \
0   40        140          289          0    172      0.0      1   
1   49        160          180          0    156      1.0      0   
2   37        130          283          0     98      0.0      1   
3   48        138          214          0    108      1.5      0   
4   54        150          195          0    122      0.0      1   

   ChestPainType_ATA  ChestPainType_NAP  ChestPainType_TA  RestingECG_Normal  \
0                  1                  0                 0                  1   
1                  0                  1                 0                  1   
2                  1                  0                 0                  0   
3                  0                  0                 0                  1   
4                  0                  1                 0                  1   

   RestingECG_ST  ExerciseAngina_Y  ST_Slope_Flat  ST_Slope_Up  
0              0                 0              0            1  
1              0                 0              1            0  
2              1                 0              0            1  
3              0                 1              1            0  
4              0                 0              0            1

In [19]:
input.shape

(918, 15)

In [20]:
target=df['HeartDisease']

In [21]:
target.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [22]:
target.shape

(918,)

In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [25]:
scaled_input = scaler.fit_transform(input)

In [27]:
scaled_input

array([[-1.4331398 ,  0.41090889,  0.82507026, ..., -0.8235563 ,
        -1.00218103,  1.15067399],
       [-0.47848359,  1.49175234, -0.17196105, ..., -0.8235563 ,
         0.99782372, -0.86905588],
       [-1.75135854, -0.12951283,  0.7701878 , ..., -0.8235563 ,
        -1.00218103,  1.15067399],
       ...,
       [ 0.37009972, -0.12951283, -0.62016778, ...,  1.21424608,
         0.99782372, -0.86905588],
       [ 0.37009972, -0.12951283,  0.34027522, ..., -0.8235563 ,
         0.99782372, -0.86905588],
       [-1.64528563,  0.30282455, -0.21769643, ..., -0.8235563 ,
        -1.00218103,  1.15067399]])

In [29]:
np.shape(scaled_input)

(918, 15)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaled_input, target, test_size=0.2, random_state=2)

In [33]:
len(X_train),len(X_test)

(734, 184)

In [34]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [36]:
lr.score(X_test,y_test)

0.842391304347826

In [37]:
lr.score(X_train,y_train)

0.8773841961852861

In [38]:
# PCA

In [43]:
from sklearn.decomposition import PCA
pca=PCA(0.90)

In [44]:
scaled_input_pca=pca.fit_transform(scaled_input)

In [45]:
scaled_input_pca

array([[ 3.1402362 , -0.42350279, -0.64563841, ..., -0.90909348,
        -0.08335011,  0.28938107],
       [ 0.23236559, -1.09015917, -0.77834553, ..., -0.94692068,
         1.40012916,  0.97167145],
       [ 1.65293842,  2.15351134, -0.30496793, ..., -1.15415068,
        -0.12727282, -0.54497203],
       ...,
       [-1.74810152, -1.4884599 ,  0.33744274, ..., -0.06964515,
         0.25658839,  0.04853522],
       [ 1.10315428,  0.2074868 , -1.7572611 , ..., -0.31440412,
        -0.53709022,  1.17486636],
       [ 2.52724324, -0.47874292,  0.95291862, ..., -0.91670795,
         0.82703874,  0.12410967]])

In [46]:
scaled_input_pca.shape

(918, 11)

In [47]:
pca.explained_variance_ratio_

array([0.22586656, 0.11008684, 0.0946602 , 0.08202286, 0.07477575,
       0.0709148 , 0.06266947, 0.05485375, 0.05125547, 0.044232  ,
       0.04085286])

In [48]:
pca.n_components_

11

In [49]:
X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(scaled_input_pca,target,test_size=0.2,random_state=2)

In [50]:
len(X_train_pca)

734

In [51]:
len(X_test_pca)

184

In [52]:
lr_pca = LogisticRegression(max_iter=10000)
lr_pca.fit(X_train_pca, y_train_pca)

LogisticRegression(max_iter=10000)

In [53]:
lr_pca.score(X_test_pca,y_test_pca)

0.8804347826086957

In [54]:
lr_pca.score(X_train_pca,y_train_pca)

0.8732970027247956