In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
df.bedrooms.median()

3.5

In [4]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [5]:
df.bedrooms.fillna(median_bedrooms, inplace=True)

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [8]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_

383724.99999999977

In [10]:
reg.predict([[3000,3,40]])

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [11]:
price = reg.coef_[0]*3000 + reg.coef_[1]*3 + reg.coef_[2]*40 +reg.intercept_
price

444400.0

In [12]:
#Exercise

In [13]:
hiring_df = pd.read_csv('hiring.csv')

In [14]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
hiring_df.experience.fillna('one',inplace = True)

In [16]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        one                    8.0                           9      50000
1        one                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [18]:
from word2number import w2n
hiring_df.experience = hiring_df.experience.apply(w2n.word_to_num)

In [19]:
hiring_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           1                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [20]:
hiring_df['test_score'] =hiring_df['test_score(out of 10)']

In [21]:
hiring_df.drop('test_score(out of 10)',axis = 1,inplace=True)

In [22]:
hiring_df

experience  interview_score(out of 10)  salary($)  test_score
0           1                           9      50000         8.0
1           1                           6      45000         8.0
2           5                           7      60000         6.0
3           2                          10      65000        10.0
4           7                           6      70000         9.0
5           3                          10      62000         7.0
6          10                           7      72000         NaN
7          11                           8      80000         7.0

In [23]:
hiring_df.test_score.mean()

7.857142857142857

In [24]:
hiring_df.test_score.fillna(hiring_df.test_score.mean(),inplace = True)

In [25]:
hiring_df

experience  interview_score(out of 10)  salary($)  test_score
0           1                           9      50000    8.000000
1           1                           6      45000    8.000000
2           5                           7      60000    6.000000
3           2                          10      65000   10.000000
4           7                           6      70000    9.000000
5           3                          10      62000    7.000000
6          10                           7      72000    7.857143
7          11                           8      80000    7.000000

In [26]:
hiring_linear_obj = linear_model.LinearRegression()

In [27]:
hiring_linear_obj.fit(hiring_df[['experience','test_score','interview_score(out of 10)']],hiring_df['salary($)'] )

LinearRegression()

In [28]:
hiring_linear_obj.predict([[6,9,10]])

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73560.60286312])

In [29]:
hiring_df.dtypes

experience                      int64
interview_score(out of 10)      int64
salary($)                       int64
test_score                    float64
dtype: object

In [30]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(hiring_linear_obj,f)

In [31]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [32]:
mp.predict([[6,9,10]])

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73560.60286312])

In [34]:
#Saving a model using joblib

from joblib import dump, load
dump(hiring_linear_obj, 'model_joblib')

['model_joblib']

In [35]:
model2 = load('model_joblib')

In [36]:
model2.predict([[6,9,10]])

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73560.60286312])

In [41]:
import pickle
s =pickle.dumps(hiring_linear_obj)
s2 =pickle.loads(s)

In [42]:
s2.predict([[6,9,10]])

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([73560.60286312])