In [5]:
import numpy as np
import sys

Benefits of Numpy array over python list-

less memory,
fast,
Convinient

comparing python list and numpy array

In [7]:
list = range(1000)
print(sys.getsizeof(5) * len(list))  # Calculating the space occupied by 1 element ('5') and then multiplying with total elements in the list

28000


In [9]:
type(list)

range

In [10]:
array = np.arange(1000)
type(array)

numpy.ndarray

In [12]:
array = np.arange(1000)
print(array.size * array.itemsize) # Calculating the space occupied by 1 element(array.itemsize) and then multiplying with total elements in the list(array.size)

4000


### We can clearly see that numpy occupies less space than normal python list

In [30]:
import time

SIZE=100000000

l1= range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2= np.arange(SIZE)

start= time.time()

result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took :",(time.time()-start))

Python list took : 29.508320808410645


In [31]:
start = time.time()

result = a1+a2
print("Numpy array took :", time.time()-start)

Numpy array took : 2.853597402572632


### we can clearly see that numpy is 10 times faster than normal python list

In [35]:
l1

range(0, 100000000)

In [36]:
zip(l1,l2)

In [37]:
print(zip(l1,l2))

In [47]:
list=[1,2,3,4]
list2=[5,6,7,8]
list+list2  

[1, 2, 3, 4, 5, 6, 7, 8]

If we normally try to add two lists using '+' it basically appends the value at 2nd list to 1st list. SO to add the corresponding elements of the list we need to add as below

In [48]:
[x+y for x,y in zip(list,list2)]

[6, 8, 10, 12]

In [51]:
type([1])

list

In [52]:
type((1))

int

1 dimensional array and accesing it

In [53]:
a=np.array([1,5,9,16,25])

In [54]:
a

array([ 1,  5,  9, 16, 25])

In [55]:
a[0]

1

In [56]:
a[4]

25

In [62]:
a.ndim

1

In [58]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [71]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
b.ndim

2

In [60]:
b[1]

array([4, 5, 6])

In [61]:
b[1][2]

6

In [63]:
b.itemsize

4

In [64]:
a.itemsize

4

In [65]:
a.dtype

dtype('int32')

In [66]:
b.dtype

dtype('int32')

In [67]:
c= np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)

In [68]:
c.dtype

dtype('float64')

In [69]:
c.itemsize

8

In [70]:
c

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [72]:
a.size

5

In [73]:
b.size

9

In [74]:
c.size

9

In [75]:
a.shape

(5,)

In [76]:
b.shape

(3, 3)

In [77]:
c.shape

(3, 3)

In [78]:
d= np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=complex)

In [79]:
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [80]:
d.dtype

dtype('complex128')

In [82]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [83]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [84]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [85]:
np.arange(1,5)

array([1, 2, 3, 4])

In [86]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(1,10,2)  # stpe size

array([1, 3, 5, 7, 9])

In [91]:
#linearly spaced numbers

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [92]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [93]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [94]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
a.shape

(3, 3)

In [96]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [100]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [103]:
b = np.array([[1,2],[4,5],[6,9]])
b

array([[1, 2],
       [4, 5],
       [6, 9]])

In [104]:
b.shape

(3, 2)

In [105]:
b.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [6],
       [9]])

In [106]:
b.reshape(1,6)

array([[1, 2, 4, 5, 6, 9]])

In [107]:
b.reshape(2,3)

array([[1, 2, 4],
       [5, 6, 9]])

In [108]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a.ravel() # flattens the array and makes it 1 dimensional

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,0]])
x

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [112]:
x.shape

(5, 2)

In [113]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [138]:
x.reshape(1,2,5)

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]]])

In [140]:
x.reshape(1,1,2,5)

array([[[[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 0]]]])

In [139]:
x.reshape(1,2,5).ndim

3

In [116]:
x.ravel().shape

(10,)

In [117]:
x.min()

0

In [118]:
x.max()

9

In [119]:
x.sum()

45

axis '0' is columns and axis '1' is rows

In [120]:
x.sum(axis=0)

array([25, 20])

In [121]:
x.sum(axis=1)

array([ 3,  7, 11, 15,  9])

In [123]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 0.        ]])

In [124]:
np.std(x)

2.8722813232690143

In [125]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,1,2],[2,3,4],[5,6,7]])

In [128]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 1, 2],
        [2, 3, 4],
        [5, 6, 7]]))

In [126]:
a+b

array([[ 2,  3,  5],
       [ 6,  8, 10],
       [12, 14, 16]])

In [129]:
a-b

array([[0, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [130]:
a*b

array([[ 1,  2,  6],
       [ 8, 15, 24],
       [35, 48, 63]])

In [131]:
a/b

array([[1.        , 2.        , 1.5       ],
       [2.        , 1.66666667, 1.5       ],
       [1.4       , 1.33333333, 1.28571429]])

In [133]:
a.dot(b) # matrix Multiplication

array([[ 20,  25,  31],
       [ 44,  55,  70],
       [ 68,  85, 109]])

In [134]:
a3 = np.array([
               [[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [20, 21, 22]],
               [[10, 12, 13],
                [14, 15, 16],
                [17, 18, 19],
                [7, 8, 9]]
               ])

In [136]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [20, 21, 22]],

       [[10, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [ 7,  8,  9]]])

In [137]:
a3.ndim

3

In [141]:
a= np.array([1,2,3,4,5])

In [144]:
a[0:3]

array([1, 2, 3])

In [145]:
a[:]

array([1, 2, 3, 4, 5])

In [146]:
a[-1]

5

In [147]:
a[-2]

4

In [149]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [150]:
a[1,2]

6

In [152]:
a[:2,2]

array([3, 6])

In [153]:
a[-1]

array([7, 8, 9])

In [155]:
a[-1,0:2]

array([7, 8])

In [156]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [157]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [159]:
for row in a:
    for element in row:
        print(element)
    

1
2
3
4
5
6
7
8
9


In [160]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [162]:
a= np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [163]:
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [164]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [165]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [166]:
a = np.arange(30).reshape(2,15)

In [167]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [177]:
result =np.hsplit(a,3)

In [178]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [179]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [180]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [181]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [183]:
result =np.vsplit(a,2)

In [184]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [185]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Indexing with boolean array

In [187]:
a=np.arange(12).reshape(3,4)

In [188]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
b=a>4

In [190]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [191]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [192]:
a[b]=-1

In [193]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [194]:
a= np.arange(12).reshape(3,4)

In [195]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
for row in a:
    for cell in row: 
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [200]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [203]:
for x in np.nditer(a,order='C'):  # C order
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [204]:
for x in np.nditer(a,order='F'):  # Fortran order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [206]:
for x in np.nditer(a,order='F',flags=['external_loop']):  # Fortran order
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [208]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [210]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

Iterating 2 arrays simultaneously

In [211]:
a=np.arange(3,15,4).reshape(3,1)

In [ ]:
b=np.arange(3,15,4).reshape(3,1)