In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
from sklearn.datasets import load_digits

In [4]:
digits  = load_digits()

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [8]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
df = pd.DataFrame(data = digits.data,columns = digits.feature_names)
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [11]:
df['target'] = digits.target

In [12]:
df.head(3)

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  

[3 rows x 65 columns]

In [18]:
df.shape

(1797, 65)

In [17]:
X=df.drop(['target'],axis='columns')
X.head(2)

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  

[2 rows x 64 columns]

In [19]:
X.shape

(1797, 64)

In [16]:
y=df['target']
y.head(2)

0    0
1    1
Name: target, dtype: int32

In [20]:
y.shape

(1797,)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=100)

In [25]:
X_train.shape

(1437, 64)

In [26]:
X_test.shape

(360, 64)

In [29]:
lr=LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9694444444444444

In [30]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


0.9916666666666667

In [44]:
clf = RandomForestClassifier(n_estimators=10)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9444444444444444

In [33]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [56]:
for train_index,test_index in kf.split([100,201,123,134,45,6,7,28,19]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [38]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [40]:
get_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),X_train,X_test,y_train,y_test)

0.9694444444444444

In [51]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9916666666666667

In [49]:
get_score(RandomForestClassifier(n_estimators=10), X_train, X_test, y_train, y_test)

0.9388888888888889

In [52]:
from sklearn.model_selection import StratifiedKFold

In [53]:
folds = StratifiedKFold(n_splits=3)

In [62]:
scores_l=[]
scores_S=[]
scores_R=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),X_train,X_test,y_train,y_test))
    scores_R.append(get_score(RandomForestClassifier(n_estimators=10), X_train, X_test, y_train, y_test))
    scores_S.append(get_score(SVC(),X_train,X_test,y_train,y_test))
print(scores_l)
print(scores_R)
print(scores_S)

[0.9282136894824707, 0.9398998330550918, 0.9165275459098498]
[0.8914858096828047, 0.9282136894824707, 0.9048414023372288]
[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]


In [68]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='lbfgs',class_weight='balanced', max_iter=10000),digits.data,digits.target,cv=3)

array([0.92487479, 0.93823038, 0.92320534])

In [69]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [71]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv=3)

array([0.9048414 , 0.91318865, 0.89816361])